
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\User\Documents\Project\ecomm_finance_converter\ecommautomation_env\Tkinter-Designer-master\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("700x550")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 550,
    width = 700,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    350.0,
    275.0,
    image=image_image_1
)

canvas.create_rectangle(
    0.0,
    0.0,
    700.0,
    71.0,
    fill="#6EC8C3",
    outline="")

canvas.create_rectangle(
    0.0,
    497.0,
    700.0,
    550.0,
    fill="#6EC8C3",
    outline="")

canvas.create_text(
    103.0,
    13.0,
    anchor="nw",
    text="ECOMMS AUTOMATION SYSTEM",
    fill="#1D4916",
    font=("Inter Bold", 30 * -1)
)

canvas.create_rectangle(
    0.0,
    69.0,
    195.0,
    497.0,
    fill="#000000",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=609.0,
    y=504.0,
    width=62.0,
    height=40.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=435.0,
    y=504.0,
    width=87.0,
    height=40.0
)

canvas.create_rectangle(
    7.0,
    504.0,
    215.0,
    544.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    221.0,
    504.0,
    429.0,
    544.0,
    fill="#000000",
    outline="")
window.resizable(False, False)
window.mainloop()
